### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel

### ISSUE THREAD

**Issue by cassignment** [googlesamples/androidtv-sample-inputs#1]
Hi,

I am compiled the code and trying to run the application on my phone and virtual avd device.
I get the following exception:

02-19 18:05:49.280  22014-22014/com.example.karunakar.tif I/art﹕ Late-enabling -Xcheck:jni
02-19 18:05:49.663  22014-22044/com.example.karunakar.tif D/OpenGLRenderer﹕ Render dirty regions requested: true
02-19 18:05:49.687  22014-22014/com.example.karunakar.tif D/Atlas﹕ Validating map...
02-19 18:05:49.772  22014-22044/com.example.karunakar.tif I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107_msm8226_LA.BF.1.1__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.01.03
    Build Date: 10/28/14 Tue
    Local Branch:
    Remote Branch: quic/l_LNX.LA.3.6
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107 + cb93e16 + f50fe49 + d7c18e6 + 5b9a565 + 0f3a25d + 607156e + 75511aa + e4d16c0 + 686f3eb + 211a271 + dd281ee +  NOTHING
02-19 18:05:49.781  22014-22044/com.example.karunakar.tif I/OpenGLRenderer﹕ Initialized EGL, version 1.4
02-19 18:05:49.815  22014-22044/com.example.karunakar.tif D/OpenGLRenderer﹕ Enabling debug mode 0
02-19 18:05:51.301  22014-22014/com.example.karunakar.tif E/ActivityThread﹕ Failed to find provider info for android.media.tv
02-19 18:05:51.302  22014-22014/com.example.karunakar.tif E/ActivityThread﹕ Failed to find provider info for android.media.tv
02-19 18:05:51.302  22014-22014/com.example.karunakar.tif D/AndroidRuntime﹕ Shutting down VM
02-19 18:05:51.306  22014-22014/com.example.karunakar.tif E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.karunakar.tif, PID: 22014
    java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
            at android.content.ContentResolver.insert(ContentResolver.java:1203)
            at com.example.android.sampletvinput.simple.SimpleTvInputSetupActivity.registerChannels(SimpleTvInputSetupActivity.java:84)
            at com.example.android.sampletvinput.simple.SimpleTvInputSetupActivity.access$000(SimpleTvInputSetupActivity.java:36)
            at com.example.android.sampletvinput.simple.SimpleTvInputSetupActivity$MyAlertDialogFragment$2.onClick(SimpleTvInputSetupActivity.java:104)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:160)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

Kindly please help.

Thanks,
KM

**Comment by shawngit** [comment]
You cannot run the sample app on any device without the TV Input Framework.  You'd need to have the following feature: http://developer.android.com/reference/android/content/pm/PackageManager.html#FEATURE_LIVE_TV.  You could use a e.g. Nexus Player device.

**Comment by cassignment** [comment]
Thanks Shawn. I think my best bet is to use android studio virtual avd for TV. Isnt?

**Comment by shawngit** [comment]
Indeed if you don't have a such device, your best bet is to use TV emulator.  See more details here:
https://developer.android.com/training/tv/start/start.html#run
