### ISSUE TITLE
Sample crashes on N preview emulator

### ISSUE THREAD

**Issue by gramound** [googlesamples/androidtv-sample-inputs#10]
The sample works well on M, but on N, when I enter the TV app, I get this exception:

05-29 20:24:18.523 2569-2569/com.android.tv E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.android.tv, PID: 2569
                                                              java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
                                                                  at android.support.v7.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:10453)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3256)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3059)
                                                                  at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1469)
                                                                  at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1533)
                                                                  at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1454)
                                                                  at com.android.tv.guide.TimelineRow.scrollTo(TimelineRow.java:59)
                                                                  at com.android.tv.guide.TimelineRow.onRtlPropertiesChanged(TimelineRow.java:67)
                                                                  at android.view.View.resolvePadding(View.java:15192)
                                                                  at android.view.ViewGroup.resolvePadding(ViewGroup.java:6607)
                                                                  at android.view.View.getPaddingLeft(View.java:18752)
                                                                  at android.support.v7.widget.RecyclerView$LayoutManager.getPaddingLeft(RecyclerView.java:7425)
                                                                  at android.support.v7.widget.OrientationHelper$1.getStartAfterPadding(OrientationHelper.java:269)
                                                                  at android.support.v7.widget.LinearLayoutManager$AnchorInfo.assignCoordinateFromPadding(LinearLayoutManager.java:2194)
                                                                  at android.support.v7.widget.LinearLayoutManager.updateAnchorInfoForLayout(LinearLayoutManager.java:734)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:486)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3239)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3048)
                                                                  at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1469)
                                                                  at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1533)
                                                                  at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1454)
                                                                  at com.android.tv.guide.TimelineRow.scrollTo(TimelineRow.java:59)
                                                                  at com.android.tv.guide.TimelineRow.onRtlPropertiesChanged(TimelineRow.java:67)
                                                                  at android.view.View.resolvePadding(View.java:15192)
                                                                  at android.view.ViewGroup.resolvePadding(ViewGroup.java:6607)
                                                                  at android.view.ViewGroup.resolvePadding(ViewGroup.java:6612)
                                                                  at android.view.ViewGroup.resolvePadding(ViewGroup.java:6612)
                                                                  at android.view.ViewGroup.resolvePadding(ViewGroup.java:6612)
                                                                  at android.view.View.resolveRtlPropertiesIfNeeded(View.java:14943)
                                                                  at android.view.ViewGroup.resolveRtlPropertiesIfNeeded(ViewGroup.java:6534)
                                                                  at android.view.View.setLayoutDirection(View.java:8177)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1507)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1240)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6298)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5969)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)

**Comment by wudongjiang333** [comment]
how to fix ? please tell me
