### ISSUE TITLE
I'm trying to run this app on a this set top box device and I get null pointer exception when I try to search for channels

### ISSUE THREAD

**Issue by timolehto** [googlesamples/androidtv-sample-inputs#3]
The device has Android 5.0 and it's attached to a DVB-T antenna and to a screen via HDMI.

The trace is always something like this:

```
com.example.android.sampletvinput E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.sampletvinput, PID: 4006
    java.lang.IllegalArgumentException: the bind value at index 1 is null
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.insert(ContentProviderNative.java:475)
            at android.content.ContentResolver.insert(ContentResolver.java:1207)
            at com.example.android.sampletvinput.TvContractUtils.updateChannels(TvContractUtils.java:109)
            at com.example.android.sampletvinput.rich.RichSetupFragment.setupChannels(RichSetupFragment.java:211)
            at com.example.android.sampletvinput.rich.RichSetupFragment.access$800(RichSetupFragment.java:61)
            at com.example.android.sampletvinput.rich.RichSetupFragment$SetupRowTask$1.onActionClicked(RichSetupFragment.java:174)
            at android.support.v17.leanback.widget.DetailsOverviewRowPresenter$ViewHolder$3$1.onClick(DetailsOverviewRowPresenter.java:154)
            at android.view.View.performClick(View.java:4756)
            at android.view.View.onKeyUp(View.java:8935)
            at android.widget.TextView.onKeyUp(TextView.java:5937)
            at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
            at android.view.View.dispatchKeyEvent(View.java:8338)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:617)
            at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:37)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:617)
            at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:27)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1600)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2306)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1682)
            at android.app.Activity.dispatchKeyEvent(Activity.java:2699)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2221)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3918)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3880)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.Vie
```

The cause is probably that this line in onCreate returns null:
```
mInputId = getIntent().getStringExtra(TvInputInfo.EXTRA_INPUT_ID);
```

Why, what, how? Any help would be appreciated.

**Comment by timolehto** [comment]
Oh, I see the problem is that this is not a full example to be run and the Actions are not intended to be launched by your self. Instead it expects some dependencies. Installing the exoplayer was easy peasy, but how do install this Live Channels app? The box has no play store and I can't find the source or apk for this app (and no, it's not preinstalled or at least it doesn't show up with `adb shell 'pm list packages -f'`).

**Comment by seventhmoon** [comment]
This app is for Android TV, which is different from most STB in the market.

Android TV is also Android, but with a little bit more.

So, those more are that your STB is missing.

**Comment by keyboardsurfer** [comment]
This seems to be related to #1 .
Please re-open and comment if not.
