### ISSUE TITLE
SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by ankitch29** [googlesamples/androidtv-sample-inputs#32]
Hi,
This sample is working fine on emulator but when I am installing apk on TV(Real device), Then i am getting this error, 

> 10-22 19:17:03.687  2538  4411 E AndroidRuntime: FATAL EXCEPTION: IntentService[EpgDataCleanupService]
10-22 19:17:03.687  2538  4411 E AndroidRuntime: Process: com.android.providers.tv, PID: 2538
10-22 19:17:03.687  2538  4411 E AndroidRuntime: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1502)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at com.android.providers.tv.TvProvider.delete(TvProvider.java:902)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.content.ContentProvider$Transport.delete(ContentProvider.java:340)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.content.ContentResolver.delete(ContentResolver.java:1371)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at com.android.providers.tv.EpgDataCleanupService.clearOldPrograms(EpgDataCleanupService.java:80)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at com.android.providers.tv.EpgDataCleanupService.onHandleIntent(EpgDataCleanupService.java:59)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-22 19:17:03.687  2538  4411 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Fleker** [comment]
It looks like your device has very low storage.

**Comment by stari4ek** [comment]
Hi,

This issue is totally Philips-specific and it is not related to disk space.
Multiple users of TVirl (https://play.google.com/store/apps/details?id=by.stari4ek.tvirl) reported it

In my case this error arise when user uninstalls app\tv-input-service and installs it once again.
```
android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:175)
	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:158)
	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:520)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:438)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1315)
	at by.stari4ek.iptv4atv.tvinput.tvcontract.a.e.a(ActionRemoveChannelsBatch.java:11)
	at by.stari4ek.iptv4atv.tvinput.tvcontract.a.e.accept(ActionRemoveChannelsBatch.java:1)
	at by.stari4ek.iptv4atv.tvinput.tvcontract.c.g.a(ChannelsInstaller.java:6)
	at by.stari4ek.iptv4atv.tvinput.tvcontract.c.b.apply(lambda)
	at g.b.e.e.b.J$a.poll(FlowableMap.java:2)
	at g.b.e.e.b.n$a.poll(FlowableDoOnEach.java:1)
	at g.b.e.e.b.u$b.poll(FlowableFilter.java:3)
```

**Comment by dlik01** [comment]
Hi, I also get this error, it plays on my android 7 when clearing the Tv Storage cache and data

`2019-08-02 15:28:05.598 5003-5033/com.android.providers.tv E/SQLiteLog: (1032) statement aborts at 130: [UPDATE channels SET app_link_color=?,searchable=?,internal_provider_data=?,network_affiliation=?,display_number=?,transport_stream_id=?,service_id=?,app_link_icon_uri=?,display_name=?
2019-08-02 15:28:05.600 5003-5033/com.android.providers.tv E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1579)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
        at com.android.providers.tv.TvProvider.update(TvProvider.java:890)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:356)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:222)
        at android.os.Binder.execTransact(Binder.java:565)
`

**Comment by dlik01** [comment]
Same problem with my  Android TV Box: 
-amLogic t95n 
-Android 7 
-3 GB free Flash memory. 
-Tv Storage v7.1.2. 
After clearing the cache and data, I've got a write error appears to sql


```
2019-08-02 17:42:02.179 5013-6845/com.android.providers.tv E/SQLiteLog: (1032) statement aborts at 130: [UPDATE channels SET app_link_color=?,searchable=?,internal_provider_data=?,network_affiliation=?,display_number=?,transport_stream_id=?,service_id=?,app_link_icon_uri=?,display_name=?
2019-08-02 17:42:02.181 5013-6845/com.android.providers.tv E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1579)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
        at com.android.providers.tv.TvProvider.update(TvProvider.java:890)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:356)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:222)
        at android.os.Binder.execTransact(Binder.java:565)
2019-08-02 17:42:02.182 6192-6192/net.intersvyaz.tv D/EpgSyncJobService: taskFinished(1)
2019-08-02 17:42:02.182 6192-6192/net.intersvyaz.tv D/EpgSyncJobService: Send out broadcast
2019-08-02 17:42:02.184 6192-6192/net.intersvyaz.tv D/RichTvInputSessionImpl: BroadcastReceiver received epg sync finished
2019-08-02 17:42:02.188 6192-6192/net.intersvyaz.tv D/EpgSyncJobService: Scheduling result is 1
2019-08-02 17:42:02.188 6192-6192/net.intersvyaz.tv D/EpgSyncJobService: Job has been scheduled for every 43200000ms
2019-08-02 17:42:02.188 6192-7389/net.intersvyaz.tv D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
2019-08-02 17:42:02.290 6192-7389/net.intersvyaz.tv W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
2019-08-02 17:42:02.290 6192-7389/net.intersvyaz.tv W/System.err: SLF4J: Defaulting to no-operation MDCAdapter implementation.
2019-08-02 17:42:02.290 6192-7389/net.intersvyaz.tv W/System.err: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
    
    --------- beginning of crash
2019-08-02 17:42:02.409 6192-7389/net.intersvyaz.tv E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: net.intersvyaz.tv, PID: 6192
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: android.database.sqlite.SQLiteException: attempt to write a readonly database (code 1032)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.update(ContentProviderNative.java:568)
        at android.content.ContentResolver.update(ContentResolver.java:1409)
        at com.google.android.media.tv.companionlibrary.utils.TvContractUtils.updateChannels(TvContractUtils.java:146)
        at com.google.android.media.tv.companionlibrary.EpgSyncJobService$EpgSyncTask.doInBackground(EpgSyncJobService.java:406)
        at com.google.android.media.tv.companionlibrary.EpgSyncJobService$EpgSyncTask.doInBackground(EpgSyncJobService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```
